sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bh8WXl9twCC7uWlBScURifWsFU7qKOpG6LksVb3tEF6vc4en9qD+mTAGD+0AdD3CwcmO+k/w+K7Gh/lavlfQBwUfmyTNskC7MTyswQFtSGx2wWCFfP3i+WTAtKJIuPK5EJUEclOPCGi0iO4LIrgaQvIJUWQLO9pVW1TYJ849prcChebBFLvRwYU08a10QL1VNBH/QFrviy6OzCCCYfqrqQI2yijhoilHwlpFUrwZokEbjQ7I/AM8Z92L6kLp9uPRfaulogr0rll9VYPupwlTqKSdPz7Zf8E1B2fx4CdaanaT77kIR7Y0Lg4MMi/ifTcqJh3J25Hemse0xqxk67EBj6aneQIUzncYq9hqQIQ36VY820z/AtOTROKfQZlyrlpQOXtgEwH5X1JKXxqNRPZlWelcTOXXKt3cKNX3b7Y+UsTNpI/MtWW9XGeTzVJwBJ5bHYbUggZUQcdKb62RkUfa9Pu+IaKF4hgoM+iPjIABWqsew6rW78Jw/leNPOvevD8VrOyIpz3JPLVBriVLF3oBLGYVVlrwVYY9OGDHyz/zUjb9wvWBLiX1JwhsW3N1v3gboVcTyZYXOo94X6IvdLlWCUpJLBifjXLZSu6ItfRPG8tVhJ/33Y/kCcNA1ZkGnOK4K7clhVQ8kfZJ1Pah7K/TDa8r+8qWmChdIAriKtRIcgI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Fortunes-and-Misfortunes-of-the-Famous-Moll-Flanders_370
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy